trigger: 
  branches: 
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: githubRepo
      type: github
      name: ROV-troos/test-azure-dev-ops
      ref: main
      endpoint: ROV-troos   # GitHub service connection

stages:
  - stage: CopyMainToTest
    displayName: "Kopieer GitHub main naar Azure DevOps test branch"
    jobs:
      - job: GitBranchSync
        displayName: "Maak en push test branch"
        steps:
          - checkout: githubRepo

          - script: |
              git config user.email "azure-pipeline@example.com"
              git config user.name "Azure Pipeline"
            displayName: "Configureer Git"

          - script: |
              if git show-ref --verify --quiet refs/heads/test; then
                echo "Local branch 'test' bestaat al"
                git checkout test
              else
                echo "Maak nieuwe lokale branch 'test'"
                git checkout -b test
              fi

              echo "Actieve branch:"
              git branch
            displayName: "Maak lokale test branch"

          - script: |
              echo "Probeer push met verschillende URL-varianten..."

              set -e  # stop bij fout
              SUCCESS=0

              for REMOTE in \
                "https://$(System.AccessToken)@dev.azure.com/spfbeheer/InSeDa/_git/InSeDa" \
                "https://$(System.AccessToken)@spfbeheer.visualstudio.com/InSeDa/_git/InSeDa"
              do
                echo "==> Test remote: $REMOTE"
                git remote remove azure || true
                git remote add azure $REMOTE

                if git push -u azure test --force; then
                  echo "✅ Push geslaagd met: $REMOTE"
                  SUCCESS=1
                  break
                else
                  echo "❌ Push gefaald met: $REMOTE"
                fi
              done

              if [ $SUCCESS -eq 0 ]; then
                echo "❌ Geen van de URL's werkte."
                exit 1
              fi
            displayName: "Push test branch naar Azure DevOps (probeer meerdere URL's)"
            env:
              System_AccessToken: $(System.AccessToken)
