trigger: 
  branches: 
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: githubRepo
      type: github
      name: ROV-troos/test-azure-dev-ops
      ref: main
      endpoint: ROV-troos

stages:
  - stage: Test
    displayName: "Test GitHub integration"
    jobs:
      - job: GitRemap
        steps:
          - checkout: githubRepo
          - script: |
              # Check of test lokaal bestaat, zo niet maak hem aan
              if git show-ref --verify --quiet refs/heads/test; then
                echo "Local branch 'test' bestaat al"
                git checkout test
              else
                echo "Maak nieuwe lokale branch 'test'"
                git checkout -b test
              fi

              echo "Actieve branch:"
              git branch
            displayName: "Zorg dat lokale test branch bestaat"
