trigger: 
  branches: 
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: githubRepo
      type: github
      name: ROV-troos/test-azure-dev-ops
      ref: main
      endpoint: ROV-troos   # GitHub service connection

stages:
  - stage: CopyMainToTest
    displayName: "Kopieer GitHub main naar Azure DevOps test branch"
    jobs:
      - job: GitBranchSync
        displayName: "Maak en push test branch"
        steps:
          # Haal GitHub repo binnen
          - checkout: githubRepo

          # Configureer Git identity
          - script: |
              git config user.email "azure-pipeline@example.com"
              git config user.name "Azure Pipeline"
            displayName: "Configureer Git"

          # Zorg dat lokale branch 'test' bestaat
          - script: |
              if git show-ref --verify --quiet refs/heads/test; then
                echo "Local branch 'test' bestaat al"
                git checkout test
              else
                echo "Maak nieuwe lokale branch 'test'"
                git checkout -b test
              fi

              echo "Actieve branch:"
              git branch
            displayName: "Maak lokale test branch"

          # Push branch 'test' naar Azure DevOps repo
          - script: |
              echo "Voeg Azure DevOps repo toe als remote"
              git remote add azure https://$(System.AccessToken)@dev.azure.com/spfbeheer/InSeDa/_git/InSeDa

              echo "Push branch 'test' naar Azure DevOps"
              git push -u azure test --force
            displayName: "Push test branch naar Azure DevOps"
            env:
              System_AccessToken: $(System.AccessToken)
