trigger: 
  branches: 
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: githubRepo
      type: github
      name: ROV-troos/test-azure-dev-ops
      ref: main
      endpoint: GitHubConnection

stages:
  - stage: Test
    displayName: "Test GitHub integration"
    jobs:
      - job: GitRemap
        steps:
          - checkout: githubRepo
          - script: |
              git remote add azure https://$(System.AccessToken)@dev.azure.com/{org}/{project}/_git/{repo}
              git push azure test
            displayName: "Push test branch naar Azure DevOps"
